#!/bin/bash

[ -f ./c0.vba ] && rm ./c0.vba

cp $HOME/.vim/syntax/c0.vim   ../syntax/
cp $HOME/.vim/ftdetect/c0.vim ../ftdetect/
cp $HOME/.vim/compiler/c0.vim ../compiler

vim -c '%MkVimball c0' -c 'q' files
